application: nusrollinggo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/login_required
  script: rollinggo.app

- url: /
  script: rollinggo.app

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /.*
  script: rollinggo.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest